public enum CalculateAppLevel {
    INIT_APP,
    START_APP,
    ARITHMATIC_INPUT_FIRSTNUMBER,
    ARITHMATIC_INPUT_SECONDNUMBER,
    ARITHMATIC_INPUT_OPERATOR,
    CIRCLE_INPUT_RADIUS,
    CALCULATE_BY_TYPE,
    PRINT_RESULT,
    PRINT_RESULT_CIRCLE,
    REMOVE_FIRST_RESULT_REQ,
    PRINT_RESULTS_REQ,
    RESULTS_BY_STREAM_REQ,
    TERMINATE_REQ,
    TERMINATE_APP
}
